# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Setup
url:                 http://osagaius.com

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             ''

title:               Osa Gaius

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  I am a technologist helping build companies, whilst thinking deeply about culture.

# The tags listed as entries in the sidebar
sidebar_tags:        [thought]

# Fallback image and color if not overwritten for tag or post
image:               /public/img/marsaxlokk-138852_640.jpg
color:               '#A85641'

# Fonts
font:                '"PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:              'Osa Gaius'

  # This photo will be used in the about section
  photo:             https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAACwAAAAJGNlYTU2MzZmLWZkMTMtNDg1Zi05ZDJhLTIxNDZmMjMzNGMyNQ.jpg
  photo2x:           https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAACwAAAAJGNlYTU2MzZmLWZkMTMtNDg1Zi05ZDJhLTIxNDZmMjMzNGMyNQ.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:             |
    Hi, I'm Osa Gaius. I currently work at [Luma](http://lumahome.com), on kick-ass WiFi tech, in Atlanta, Georgia,

    I strongly believe that great technology should have a global impact. This stems from the fact that I grew up in Nigeria with little exposure to the consumer internet.

    For the last six years, I have focused deeply on web technologies, machine learning, and robotics.
    I have built and deployed complex systems in various programming languages.

    I am currently focused on building real-time consumer products using functional and reactive programming techniques.

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    # reddit:          _username_
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    github:          osayame
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    linkedin:        osagaius
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Anaylics
# google_analytics_id: 'UA-84025722-2'

# Setting a disqus subdomain will enable the comment section
# disqus:            <username>

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
